src/Entity/Program.php
<?php

namespace App\Entity;

use App\Repository\ProgramRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;



/**
 * @ORM\Entity(repositoryClass="App\Repository\ProgramRepository")
 * @UniqueEntity("title",
 *          message="ce titre existe déjà"
 * )
 */


class Program
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="N'oublie pas le titre !")
     * @Assert\Length(max="255")
     *
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="N'oublie pas le résumé !")
     * @Assert\Regex(
     *     pattern="/(plus belle la vie)/",
     *     match=false,
     *     message="On parle de vraies séries ici"
     * )
     *
     */
    private $summary;
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $poster;

    /**
     * @ORM\ManyToOne (targetEntity="App\Entity\Category", inversedBy="programs")
     * @ORM\JoinColumn (nullable=false)
     */
    private $category;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSummary(): ?string
    {
        return $this->summary;
    }

    public function setSummary(string $summary): self
    {
        $this->summary = $summary;

        return $this;
    }

    public function getPoster(): ?string
    {
        return $this->poster;
    }

    public function setPoster(?string $poster): self
    {
        $this->poster = $poster;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }


    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Season", mappedBy="program")
     */
    private $seasons;

    /**
     * @ORM\ManyToMany(targetEntity=Actor::class, mappedBy="programs")
     */
    private $actors;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $slug;


    public function __construct()
    {
        $this->seasons = new ArrayCollection();
        $this->actors = new ArrayCollection();
    }

    /**
     * @return Collection|Season[]
     */
    public function getSeasons(): Collection
    {
        return $this->seasons;
    }

    /**
     * @param Season $season
     * @return Program
     */
    public function addSeason(Program $season): self
    {
        if (!$this->seasons->contains($season)){
            $this->seasons[] = $season;
            $season->setProgram($this);
        }
        return $this;

    }

    /**
     * @param Season $season
     * @return Program
     */
    public function removeSeason(Program $season): self
    {
        if ($this->seasons->contains($season)){
            $this->seasons->removeElement($season);
            if ($season->getProgram() === $this) {
                $season->setProgram(null);
            }
        }
        return $this;
    }

    /**
     * @return Collection|Actor[]
     */
    public function getActors(): Collection
    {
        return $this->actors;
    }

    public function addActor(Actor $actor): self
    {
        if (!$this->actors->contains($actor)) {
            $this->actors[] = $actor;
            $actor->addProgram($this);
        }

        return $this;
    }

    public function removeActor(Actor $actor): self
    {
        if ($this->actors->removeElement($actor)) {
            $actor->removeProgram($this);
        }

        return $this;
    }

    /**
     * @return Collection|Actor[]
     */
    public function getActor(): Collection
    {
        return $this->actors;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="author", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }
}

src/Form/ProgramType.php
<?php

namespace App\Form;

use App\Entity\Program;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use App\Entity\Actor;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class ProgramType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class)
            ->add('summary', TextareaType::class)
            ->add('poster', UrlType::class)
            ->add('category', null, ['choice_label' => 'name'])
            ->add('actors', EntityType::class, [
                'class' => Actor::class,
                'choice_label' => 'name',
                'multiple' => true,
                'expanded' => false,
                ]);
    }


    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Program::class,
        ]);
    }
}

src/Controller/ProgramController.php
<?php
// src/Controller/ProgramController.php
namespace App\Controller;

use App\Entity\Program;
use App\Entity\Season;
use App\Entity\Episode;
use App\Entity\Comment;
use App\Form\CommentType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Form\ProgramType;
use Symfony\Component\HttpFoundation\Request;
use App\Service\Slugify;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;


/**
 * @Route("/programs", name="program_")
 */
Class ProgramController extends AbstractController
{
    /**
     * @Route("/", name="index")
     * @return Response A response instance
     */
    public function index(): Response
    {
        $programs = $this->getDoctrine()
            ->getRepository(Program::class)
            ->findAll();

        return $this->render(
            'program/index.html.twig',
            ['programs' => $programs]
        );
    }

    /**
     * The controller for the category add form
     * Display the form or deal with it
     *
     * @Route("/new", name="new", methods={"GET","POST"})
     * @throws \Symfony\Component\Mailer\Exception\TransportExceptionInterface
     */

    public function new(Request $request, Slugify $slugify, MailerInterface $mailer) : Response
    {
        // Create a new Program Object
        $program = new Program();
        // Create the associated Form
        $form = $this->createForm(ProgramType::class, $program);
        // Get data from HTTP request
        $form->handleRequest($request);
        // Was the form submitted ?
        if ($form->isSubmitted() && $form->isValid()) {
            // handle data, in example, an insert into database
            // redirection

            $entityManager = $this->getDoctrine()->getManager();
            // Persist Category Object

            $slug = $slugify->generate($program->getTitle());
            $program->setSlug($slug);

            $entityManager->persist($program);
            // Flush the persisted object
            $entityManager->flush();

            $email = (new Email())
                ->from($this->getParameter('mailer_from'))
                ->to('d0850397c7-13f7d1@inbox.mailtrap.io')
                ->subject('Une nouvelle série vient d\'être publiée !')
                ->html($this->renderView('program/newProgramEmail.html.twig', ['program' => $program]));

            $mailer->send($email);

            return $this->redirectToRoute('program_index');
        }

        return $this->render('program/new.html.twig', ["form" => $form->createView()]);
    }

    /**
     * Getting a program by id
     *
     * @Route("/{slug}", name="show")
     *
     */
    public function show(Program $program): Response
    {
        $seasons = $program->getSeasons();

        if (!$program) {
            throw $this->createNotFoundException(
                'No program with id : '.$program.' found in program\'s table.'
            );
        }
        return $this->render('program/show.html.twig',
            [
                'program'=> $program,
                'seasons' => $seasons
            ]);
    }

    /**
     * @Route("/{slug}/season/{season}", name="season_show")
     */
    public function showSeason(Program $program, Season $season): Response
    {
        $episodes = $season->getEpisodes();

        return $this->render('program/season_show.html.twig', [
            'season' => $season,
            'program' => $program,
            'episodes' => $episodes
        ]);
    }

    /**
     * @Route("/{slug}/seasons/{seasonId}/episode/{episodeSlug}", name="episode_show")
     * @ParamConverter("program", class="App\Entity\Program", options={"mapping": {"slug": "slug"}})
     * @ParamConverter("season", class="App\Entity\Season", options={"mapping": {"seasonId": "id"}})
     * @ParamConverter("episode", class="App\Entity\Episode", options={"mapping": {"episodeSlug": "slug"}})
     * @param Program $program
     * @param Season $season
     * @param Episode $episodes
     * @param Request $request
     * @return Response
     */
    public function showEpisode(Program $program, Season $season, Episode $episode, Request $request): Response
    {
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);
        $user=$this->getUser();
        $comment->setEpisode($episode);
        $comment->setAuthor($user);


        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($comment);
            $entityManager->flush();
            return $this->redirectToRoute('comment_index');
        }

        $comments=$this->getDoctrine()
            ->getRepository(Comment::class)
            ->findBy(['episode'=>$episode]);

        return $this->render('program/episode_show.html.twig', [
            'program' => $program,
            'season' => $season,
            'episode' => $episode,
            'comments'=> $comments,
            'form'=> $form->createView()
        ]);
    }
}

templates/program/episode_show.html.twig
{% extends 'layout/base.html.twig' %}

{% block title %}
    {{ program.title }} |  Saison {{ season.number }}
{% endblock %}

{%  block stylesheet %}
    {{ parent() }}
{% endblock %}

{% block body %}

    <div class="media">
        <img class="align-self-start mr-3" src="{{ program.poster }}" alt="{{ program.title }} poster">
        <div class="media-body">
            <h1 class="mt-0"> {{ program.title }} </h1>
            <h1> Saison {{ season.number }} </h1>
            <div class>
                Date de diffusion: {{ season.year }} <br>
                {{ season.description }}
            </div>
            <div><br>
                Episode {{ episode.number }}: {{ episode.title }} <br>
                {{ episode.synopsis }}

                {% if app.user %}
                    {{ include('comment/_form.html.twig') }}
                {% endif %}

                {% for comment in comments %}
                    <div>
                        <div>Commentaire  : {{ comment.comment }} </div>
                        <div>Note {{ comment.rate }}/10 </div>
                        <div>Par {{ comment.author.username }} </div>
                    </div>
                {% else %}
                    <div>
                        Pas de commentaire
                    </div>
                {% endfor %}

                <div class="retour">
                    <a href="{{ path('program_index') }}">
                        Retour à la liste des programmes
                    </a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/program/index.html.twig
{% extends 'layout/base.html.twig' %}

{% block title %}
    All programs
{% endblock %}

{% block stylesheet %}
    {{ parent() }}
{% endblock %}

{% block body %}

    <h1>Toutes les séries</h1>
    <div class="container-fluid">
        <div class="row index">
            {% for program in programs %}
                <div class="col-lg-4 program">
                    <a href="{{ path("program_show", {slug: program.slug }) }}">
                        <img class="poster" src="{{ program.poster }}" alt="Affiche {{ program.title }}">
                    </a>
                    <div class="description">
                        <h2 class="title">{{ loop.index }}/ {{ program.title }}</h2>
                        <h3> Catégorie: {{ program.category.name }}</h3>
                        <p>{{ program.summary}}</p>
                        <a href="{{ path("program_show", { slug: program.slug }) }}">
                            Voir la fiche
                        </a>
                    </div>
                </div>
            {% else %}
                Aucune série trouvée.
            {% endfor %}
        </div>
    </div>

    <div class="retour">
        <a href="{{ path('app_index') }}">
            Retour à l'acceuil
        </a>
    </div>


{% endblock %}

templates/program/new.html.twig
{% extends 'layout/base.html.twig' %}

{% block title %}
    {{ parent() }}
{% endblock %}

{% block body %}

    <h1>Ajoute une nouvelle série</h1>

    <div class="center container-fluid">
        <div class="col-lg-3">
            {{ form_start(form) }}
            {{ form_errors(form) }}
            {{ form_widget(form) }}
            <input type='submit' value='Ajouter'>
            {{ form_end(form) }}
        </div>
    </div>

{% endblock %}

templates/program/newProgramEmail.html.twig
{% extends 'layout/email.html.twig' %}

{% block title %}Un nouvel épisode t'attend!{% endblock %}

{% block body %}

        <h1>La série {{ program.title }} est disponible</h1>

        <p>Hé oh! Bonne nouvelle, la série {{ program.title }} a été ajouté sur ton site préféré Wild Series</p>

        <p>Résumé : {{program.summary}}</p>

        <p> N'attends plus et viens <a href="http://localhost:8000/programs/{{ program.slug }}"> voir la série !</a></p>

{% endblock %}

templates/program/season_show.html.twig
{% extends 'layout/base.html.twig' %}

{% block title %}
    {{ program.title }} | Saison {{ season.number }}
{% endblock %}

{% block stylesheet %}
    {{ parent() }}
{% endblock %}

{% block body %}
    <div class="media">
        <img class="align-self-start mr-3" src="{{ program.poster }}" alt="{{ program.title }} poster">
        <div class="media-body">
            <h1 class="mt-0"> {{ program.title }} </h1>
            <h1> Saison {{ season.number }} </h1>
            <div class>
                Date de diffusion: {{ season.year }} <br>
                {{ season.description }}
            </div>
            <div>
                <br>
                Liste des épisodes:
                <div class="tab"><br>
                    {% for episode in episodes %}
                        Episode {{ episode.number }}: {{ episode.title }} <br>
                        <div class="season">
                            <a href="{{ path("program_episode_show", { 'slug': program.slug, 'seasonId' : season.id, 'episodeSlug' : episode.slug}) }}"> Voir le détail de l'épisode {{ episode.number }}</a>
                        </div>
                        Episode {{ episode.number }} : {{ episode.title }}
                    {% endfor %}
                </div>
            </div>
            <div class="retour">
                <br><br>
                <a href="{{ path('program_show', {slug : program.slug}) }}">
                    Retour à la fiche du programme
                </a>
            </div>
        </div>
    </div>

{% endblock %}

templates/program/show.html.twig
{% extends 'layout/base.html.twig' %}
{% block title %}Série #{{ program.id }}{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="container">
            <div class="media">
                <img class="align-self-start mr-3" src="{{ program.poster }}" alt="{{ program.title }} poster">
                <div class="media-body">
                    <h1 class="mt-0">{{ program.title }}</h1>
                    <p>{{ program.summary }}</p>
                    <p>Catégorie : {{ program.category.name }}</p>
                    <div class="season">
                        <h4>Les saisons disponibles</h4>
                        {% for season in seasons %}
                        <div>
                            <a href="{{ path("program_season_show", { 'slug': program.slug, 'season' : season.id}) }}">
                                Saison {{ season.number }}</a> {% else %}
                                Aucune saison trouvée.
                            {% endfor %}
                        </div>
                    </div>
                    <div class="actor">
                        <strong>Acteurs :</strong>
                        <ul>
                            {% for actor in program.actors %}
                                <li><a href="{{ path('actor_show', {'id': actor.id})}}">{{ actor.name }}</a></li>
                            {% else %}
                                <li>Aucun acteur pour cette série</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>

            <a href="{{ path('program_index') }}">
                Retour à la liste des programmes
            </a>
        </div>
    </div>

{% endblock %}